CREATE TABLE autopart
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    detail_name VARCHAR(255),
    price       INTEGER,
    quantity    INTEGER,
    total       INTEGER,
    parent_id   BIGINT,
    CONSTRAINT pk_autopart PRIMARY KEY (id)
);

ALTER TABLE autopart
    ADD CONSTRAINT FK_AUTOPART_ON_PARENT FOREIGN KEY (parent_id) REFERENCES autopart (id);